name: hyperdecktransfer
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - wheel
  - setuptools
  - setuptools_scm
  - pip
  - pip:
     # add here only pip-packages that are not available in conda/conda-forge!
     - PyQt6
     - -e .  # install git checkout of hyperdecktransfer in editable mode

     # DEVELOPMENT ONLY PACKAGES
  - pyinstaller
  - pip:
     - pre_commit
